# Generated by Django 5.2.17 on 2026-09-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=30, unique=True, verbose_name='通知单编号')),
                ('doc_type', models.CharField(choices=[('transfer', '调动通知'), ('regular', '转正通知'), ('reward', '奖惩通知'), ('resign', '离职通知')], max_length=20, verbose_name='通知单类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('issue_date', models.DateField(verbose_name='签发日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_docs', to=settings.AUTH_USER_MODEL, verbose_name='涉及员工')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='签发人')),
                ('related_transfer', models.ForeignKey(blank=True, help_text='调动类通知单由调动记录自动带出前后岗位信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_docs', to='personnel.transferrecord', verbose_name='关联调动记录')),
            ],
            options={
                'verbose_name': '人事通知单',
                'verbose_name_plural': '人事通知单',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['doc_type', 'issue_date'], name='idx_doc_type_date')],
            },
        ),
    ]
