# Generated by Django 5.2.17 on 2026-09-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sysconf', '0002_employee_graduate_school_employee_major_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('transfer', '部门调动'), ('promotion', '晋升'), ('demotion', '降职'), ('salary_adjust', '调薪')], max_length=20, verbose_name='调动类型')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('reason', models.CharField(max_length=200, verbose_name='调动原因')),
                ('doc_no', models.CharField(blank=True, help_text='关联 FR-QRY-02 生成的人事变动通知单', max_length=30, verbose_name='通知单编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('after_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sysconf.department', verbose_name='新部门')),
                ('after_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sysconf.position', verbose_name='新岗位')),
                ('before_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sysconf.department', verbose_name='原部门')),
                ('before_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sysconf.position', verbose_name='原岗位')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_records', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '调动记录',
                'verbose_name_plural': '调动记录',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='考勤日期')),
                ('status', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early_leave', '早退'), ('absent', '旷工'), ('leave', '请假')], default='normal', max_length=20, verbose_name='考勤状态')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='上班打卡')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='下班打卡')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='工作时长(小时)')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-work_date'],
                'indexes': [models.Index(fields=['work_date', 'status'], name='idx_att_date_status')],
                'unique_together': {('employee', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('category', models.CharField(blank=True, help_text='取值来自数据字典', max_length=50, verbose_name='证书类别')),
                ('cert_no', models.CharField(blank=True, max_length=50, verbose_name='证书编号')),
                ('issuing_authority', models.CharField(blank=True, max_length=100, verbose_name='发证机构')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expire_date', models.DateField(blank=True, help_text='为空表示长期有效；到期前应提醒续期', null=True, verbose_name='有效期至')),
                ('attachment', models.FileField(blank=True, help_text='对应 FR-PER-01 的证书资质录入', upload_to='certificates/%Y/', verbose_name='扫描件')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '证书资质',
                'verbose_name_plural': '证书资质',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['employee', 'name'], name='idx_cert_emp_name')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', '年假'), ('sick', '病假'), ('personal', '事假'), ('marriage', '婚假'), ('maternity', '产假'), ('bereavement', '丧假')], max_length=20, verbose_name='请假类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('days', models.DecimalField(decimal_places=1, help_text='支持半天（0.5）；不自动计算，因需扣除周末与法定节假日', max_digits=5, verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假事由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已撤销')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approve_opinion', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='idx_leave_status_date'), models.Index(fields=['employee', 'status'], name='idx_leave_emp_status')],
            },
        ),
        migrations.CreateModel(
            name='RegularizationApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(verbose_name='申请日期')),
                ('original_status', models.CharField(choices=[('intern', '实习'), ('probation', '试用'), ('regular', '正式'), ('resigned', '离职')], help_text='通常为「实习」或「试用」，转正后据此判断是否合规', max_length=20, verbose_name='申请时状态')),
                ('expect_regular_date', models.DateField(verbose_name='期望转正日期')),
                ('self_evaluation', models.TextField(blank=True, verbose_name='自我评价')),
                ('department_opinion', models.TextField(blank=True, verbose_name='部门意见')),
                ('hr_opinion', models.TextField(blank=True, verbose_name='HR 意见')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_applies', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '转正申请',
                'verbose_name_plural': '转正申请',
                'ordering': ['-apply_date'],
                'indexes': [models.Index(fields=['status', 'apply_date'], name='idx_reg_status_date')],
            },
        ),
        migrations.CreateModel(
            name='RewardPunish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('reward', '奖励'), ('punish', '处罚')], max_length=20, verbose_name='类型')),
                ('happen_date', models.DateField(verbose_name='发生日期')),
                ('title', models.CharField(max_length=100, verbose_name='事项名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='奖励为正、处罚为正数并在核算时按类型决定加减', max_digits=10, verbose_name='金额(元)')),
                ('description', models.TextField(blank=True, verbose_name='详细说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_punishes', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '奖罚登记',
                'verbose_name_plural': '奖罚登记',
                'ordering': ['-happen_date'],
                'indexes': [models.Index(fields=['employee', 'happen_date'], name='idx_rp_emp_date')],
            },
        ),
        migrations.CreateModel(
            name='SocialInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='格式 YYYY-MM', max_length=7, verbose_name='缴费月份')),
                ('insurance_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='缴费基数')),
                ('pension_personal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='养老保险(个人)')),
                ('medical_personal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='医疗保险(个人)')),
                ('unemployment_personal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='失业保险(个人)')),
                ('housing_fund_personal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住房公积金(个人)')),
                ('personal_total', models.DecimalField(decimal_places=2, default=0, help_text='工资核算时作为「社保自负部分」扣减', max_digits=10, verbose_name='个人承担合计')),
                ('pension_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='养老保险(单位)')),
                ('medical_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='医疗保险(单位)')),
                ('unemployment_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='失业保险(单位)')),
                ('housing_fund_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住房公积金(单位)')),
                ('company_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单位承担合计')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_insurances', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '社保缴纳记录',
                'verbose_name_plural': '社保缴纳记录',
                'ordering': ['-period'],
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
