# Generated by Django 5.2.17 on 2026-09-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sysconf', '0002_employee_graduate_school_employee_major_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='课程编码')),
                ('course_type', models.CharField(choices=[('internal', '内部培训'), ('external', '外部培训'), ('frontline', '一线工技能培训')], max_length=20, verbose_name='课程类型')),
                ('instructor', models.CharField(blank=True, max_length=50, verbose_name='讲师')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='课时(小时)')),
                ('description', models.TextField(blank=True, verbose_name='课程简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '培训课程',
                'verbose_name_plural': '培训课程',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='培训地点')),
                ('planned_headcount', models.PositiveIntegerField(default=0, verbose_name='计划人数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ongoing', '进行中'), ('finished', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='计划状态')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='training.course', verbose_name='培训课程')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('target_departments', models.ManyToManyField(blank=True, help_text='留空表示面向全体员工', related_name='training_plans', to='sysconf.department', verbose_name='面向部门')),
            ],
            options={
                'verbose_name': '培训计划',
                'verbose_name_plural': '培训计划',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_status', models.CharField(choices=[('enrolled', '已报名'), ('attended', '已参加'), ('absent', '缺勤'), ('passed', '考核通过'), ('failed', '考核未通过')], default='enrolled', max_length=20, verbose_name='参与状态')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='考核成绩')),
                ('certificate_no', models.CharField(blank=True, max_length=50, verbose_name='结业证书编号')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='参训员工')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='training.trainingplan', verbose_name='培训计划')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['status', 'start_date'], name='idx_plan_status_date'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['employee', 'attend_status'], name='idx_tr_emp_status'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingrecord',
            unique_together={('plan', 'employee')},
        ),
    ]
