# Generated by Django 5.2.17 on 2026-09-28 08:45

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='岗位名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='岗位编码')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='岗位级别')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='岗位说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='登录名')),
                ('employee_no', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('real_name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, help_text='用于生日提醒（FR-PER-04）与年龄段统计（FR-RPT-01）', null=True, verbose_name='出生日期')),
                ('id_card', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{17}[\\dXx]$', '身份证号格式不正确（应为 18 位）')], verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号格式不正确')], verbose_name='手机号')),
                ('education', models.CharField(blank=True, choices=[('below_college', '大专以下'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='学历')),
                ('political_status', models.CharField(blank=True, help_text='取值来自数据字典', max_length=20, verbose_name='政治面貌')),
                ('native_place', models.CharField(blank=True, max_length=50, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='现住址')),
                ('employ_status', models.CharField(choices=[('intern', '实习'), ('probation', '试用'), ('regular', '正式'), ('resigned', '离职')], default='regular', max_length=20, verbose_name='在职状态')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('is_deleted', models.BooleanField(default=False, help_text='离职或误录入的档案置为 True，保留历史以便追溯，不做物理删除', verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('salary_level', models.ForeignKey(blank=True, help_text='对应 FR-SAL-01 薪酬体系配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='salary.salarylevel', verbose_name='薪酬级别')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['employee_no'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_type', models.CharField(max_length=50, verbose_name='字典类型')),
                ('dict_key', models.CharField(max_length=50, verbose_name='字典键')),
                ('dict_value', models.CharField(max_length=100, verbose_name='字典值')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'ordering': ['dict_type', 'sort_order'],
                'unique_together': {('dict_type', 'dict_key')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部门编码')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sysconf.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='sysconf.department', verbose_name='所属部门'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('url_name', models.CharField(blank=True, max_length=100, verbose_name='路由名')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标类名')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sysconf.menu', verbose_name='上级菜单')),
                ('visible_roles', models.ManyToManyField(blank=True, related_name='menus', to='auth.group', verbose_name='可见角色')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='sysconf.position', verbose_name='岗位'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'employee_no'], name='idx_emp_dept_no'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employ_status'], name='idx_emp_status'),
        ),
    ]
