# Generated by Django 5.2.17 on 2026-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='graduate_school',
            field=models.CharField(blank=True, help_text='正式员工与实习生均需填写', max_length=100, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, max_length=50, verbose_name='所学专业'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='到期未转正应触发提醒，避免实习生长期停留在实习状态（FR-PER-02）', null=True, verbose_name='实习/试用期结束日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='regular_date',
            field=models.DateField(blank=True, help_text='转正审批通过时写入，报表可按转正时间统计（FR-PER-02、FR-RPT-03）', null=True, verbose_name='转正日期'),
        ),
    ]
