# Generated by Django 5.2.17 on 2026-09-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='标准问题')),
                ('answer', models.TextField(verbose_name='标准答案')),
                ('keywords', models.CharField(help_text='多个关键词用英文逗号分隔，命中任一即视为匹配', max_length=200, verbose_name='触发关键词')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='命中次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'FAQ 知识库',
                'verbose_name_plural': 'FAQ 知识库',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='提问内容')),
                ('answer', models.TextField(verbose_name='回答内容')),
                ('source', models.CharField(choices=[('rules', '规则库'), ('template', '数据模板'), ('cloud', '云 API'), ('fallback', '离线兜底')], default='rules', max_length=20, verbose_name='应答来源')),
                ('elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='提问人')),
                ('matched_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='assistant.faqitem', verbose_name='命中的 FAQ')),
            ],
            options={
                'verbose_name': '问答记录',
                'verbose_name_plural': '问答记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='idx_chat_emp_time')],
            },
        ),
    ]
