# Generated by Django 5.2.17 on 2026-09-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date', models.DateField(verbose_name='加班日期')),
                ('overtime_type', models.CharField(choices=[('workday', '工作日'), ('weekend', '休息日'), ('holiday', '法定节假日')], max_length=10, verbose_name='加班类型')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='加班时长(小时)')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='加班事由')),
                ('salary_period', models.CharField(db_index=True, max_length=7, verbose_name='所属薪酬周期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '加班登记',
                'verbose_name_plural': '加班登记',
                'ordering': ['-overtime_date'],
            },
        ),
        migrations.CreateModel(
            name='PieceworkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_period', models.CharField(db_index=True, max_length=7, verbose_name='所属薪酬周期')),
                ('work_date', models.DateField(verbose_name='生产日期')),
                ('work_mode', models.CharField(choices=[('piecework', '计件'), ('timework', '计时')], max_length=10, verbose_name='计薪方式')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='产品 / 工序')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量(件)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/件)')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='工时(小时)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='时薪(元/小时)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='保存时按计薪方式自动计算，不由人工填写', max_digits=12, verbose_name='小计金额(元)')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计件/计时产量',
                'verbose_name_plural': '计件/计时产量',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='级别名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='级别编码')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本工资')),
                ('post_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='岗位津贴')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '薪酬级别',
                'verbose_name_plural': '薪酬级别',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_period', models.CharField(db_index=True, max_length=7, verbose_name='薪酬周期')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='基本工资')),
                ('piecework_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='计件/计时工资')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='加班费')),
                ('utility_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='水电扣费')),
                ('social_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='社保自负部分')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, help_text='由 calculate_net_pay() 按公式计算', max_digits=12, verbose_name='实发工资')),
                ('pay_status', models.CharField(choices=[('draft', '待发放'), ('paid', '已发放')], default='draft', max_length=10, verbose_name='发放状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工资档案',
                'verbose_name_plural': '工资档案',
                'ordering': ['-salary_period', 'employee__employee_no'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('overtime_workday_rate', models.DecimalField(decimal_places=2, default=1.5, help_text='按劳动法：工作日加班为基本时薪的 1.5 倍', max_digits=4, verbose_name='工作日加班倍率')),
                ('overtime_weekend_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='休息日加班倍率')),
                ('overtime_holiday_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=4, verbose_name='法定节假日加班倍率')),
                ('monthly_work_hours', models.DecimalField(decimal_places=2, default=174.0, help_text='用于把月基本工资折算为时薪，默认 21.75 天 × 8 小时', max_digits=6, verbose_name='月标准工时(小时)')),
                ('water_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='水费单价(元/吨)')),
                ('electricity_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='电费单价(元/度)')),
                ('social_insurance_ratio', models.DecimalField(decimal_places=4, default=0, help_text='如 0.105 表示个人承担 10.5%', max_digits=5, verbose_name='社保个人负担比例')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '薪酬标准配置',
                'verbose_name_plural': '薪酬标准配置',
                'ordering': ['-effective_date'],
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.CreateModel(
            name='UtilityFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_period', models.CharField(db_index=True, max_length=7, verbose_name='所属薪酬周期')),
                ('water_usage', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='用水量(吨)')),
                ('electricity_usage', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='用电量(度)')),
                ('water_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='水费(元)')),
                ('electricity_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='电费(元)')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='合计扣费(元)')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '水电费登记',
                'verbose_name_plural': '水电费登记',
                'ordering': ['-salary_period'],
            },
        ),
    ]
