# Generated by Django 5.2.17 on 2026-09-28 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records', to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='pieceworkrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='pieceworkrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piecework_records', to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='utilityfeerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_records', to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddIndex(
            model_name='overtimerecord',
            index=models.Index(fields=['employee', 'salary_period'], name='idx_ot_emp_period'),
        ),
        migrations.AddIndex(
            model_name='pieceworkrecord',
            index=models.Index(fields=['employee', 'salary_period'], name='idx_pw_emp_period'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['salary_period', 'pay_status'], name='idx_sal_period_status'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('employee', 'salary_period')},
        ),
        migrations.AlterUniqueTogether(
            name='utilityfeerecord',
            unique_together={('employee', 'salary_period')},
        ),
    ]
