# Generated by Django 5.2.17 on 2026-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='reward_punish_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='本周期奖励合计减去处罚合计，可为负（数据来自 FR-PER-03 奖罚登记）', max_digits=12, verbose_name='奖罚净额'),
        ),
    ]
